[package]
name = "makepad-book-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
# use dev branch, because it has the latest changes
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "dev" }
