[package]
name = "makepad-workshop-gosim-beijing-2024"
authors = ["Julián Montes de Oca julmontesdeoca@gmail.com"]
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-widgets = { workspace = true }
